name: Github Pages
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: head

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: yarn

      - name: Package application
        run: |
          bundle exec rake
          yarn install --frozen-lockfile
          yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
